#!/bin/bash

SMC_KEY="CH0C"
ON_VALUE="00"
OFF_VALUE="01"

usage() {
    echo "mbcharge - command line utility to control MacBook battery charging"
    echo
    echo "Usage:"
    echo "  mbcharge enable"
    echo "    Enables battery charging"
    echo
    echo "  mbcharge disable"
    echo "    Disables battery charging"
    echo
    echo "  mbcharge status"
    echo "    Show battery charging status"
}

get_smc_value() {
    # Example smc command output: "  CH0C  [hex_]  (bytes 01)"
    # Extract the raw value from output string
    smc -k $SMC_KEY -r | sed -nE 's/^.+\(bytes ([0-9a-f]+)\)/\1/p'
}

status() {
    if [[ $(get_smc_value) == $ON_VALUE ]]; then
        echo "Battery charging is enabled."
    else
        echo "Battery charging is disabled."
    fi
}

enable() {
    sudo smc -k $SMC_KEY -w $ON_VALUE
}

disable() {
    sudo smc -k $SMC_KEY -w $OFF_VALUE
}

case "$1" in
    enable)
        if [[ $(get_smc_value) != $ON_VALUE ]]; then
            enable
        fi
        ;;
    disable)
        if [[ $(get_smc_value) != $OFF_VALUE ]]; then
            disable
        fi
        ;;
    status)
        status
        ;;
    *)
        usage
        exit 1
        ;;
esac
